"""RectChr conf model, reader and writer (engine-format compatible)."""
import re
from pathlib import Path

from .schema import Schema

_ENGINE_LINE = re.compile(r"^([A-Za-z][A-Za-z0-9_\-\.]*)\s*=\s*(.*)$")

# conf keys whose values are file paths resolved against the conf directory
_PATH_KEYS = ("colormap_conf", "line_colors_conf")


def abspath_for(value, base_dir):
    """Resolve a conf path: ~ expanded, relative -> against base_dir."""
    value = str(value).strip()
    if not value:
        return value
    p = Path(value).expanduser()
    if p.is_absolute():
        return str(p)
    return str((Path(base_dir) / p).resolve())


def quote_value(value, param=None):
    """Quote a value that would otherwise be mangled by the config parser.

    NOTE the engine protects only the literal two-character sequence `"#`
    (ConfigDataLoader.pm:315-318), so a '#' anywhere else still ends the value
    early even when quoted — callers should warn the user about that case."""
    value = str(value)
    if value == "":
        return value
    p = Schema.param(param) if param else None
    if value.startswith("#") or "#" in value or (p and p.get("type") == "color"):
        return '"%s"' % value
    return value


class ConfModel:
    """In-memory representation of a RectChr configuration."""

    def __init__(self):
        self.files = [""]              # File1..FileN paths
        self.global_params = {}        # user-set global params
        self.track_all = {}            # user-set trackALL params
        # sparse explicit track sections {number(int): {param: value}};
        # sections the user never touches simply don't exist (engine defaults)
        self.tracks = {}
        # True once track_num is pinned (set in the conf, or the user added /
        # removed a track). When False we must NOT write it: the engine
        # defaults it to the number of value columns (ConfigDataLoader.pm:517)
        # so emitting max(track section) could LOWER the track count.
        self.track_num_explicit = False

    # ------------------------------------------------------------- helpers
    def section_for(self, scope):
        if isinstance(scope, int):
            return self.tracks.get(scope)
        return self.global_params if scope == "global" else (
            self.track_all if scope == "track" else None)

    def set_param(self, scope, name, value):
        if isinstance(scope, int):
            target = self.tracks.setdefault(scope, {})
        else:
            target = self.section_for(scope)
            if target is None:
                return
        if value is None or value == "":
            target.pop(name, None)
        else:
            target[name] = str(value)

    def get_param(self, scope, name):
        target = self.section_for(scope)
        return (target or {}).get(name, "")

    def sync_track_num(self):
        """Pin global.track_num to cover every configured section.

        Only runs when track_num is EXPLICIT (present in the loaded conf, or
        the user added/removed a track). Otherwise it is left absent so the
        engine keeps inferring it from the data columns — writing
        max(track section) would otherwise shrink the track count of a conf
        that never specified track_num. Raises, never lowers, matching
        ConfigDataLoader::adjust_value_x_based_on_max_level."""
        if not self.tracks or not self.track_num_explicit:
            return
        top = max(self.tracks)
        cur = self.global_params.get("track_num")
        try:
            cur_n = int(cur) if cur not in (None, "") else 0
        except (TypeError, ValueError):
            cur_n = 0
        if top > cur_n:
            self.global_params["track_num"] = str(top)

    def absolutize_paths(self, base_dir):
        """Resolve user-typed relative file paths against the working dir
        before saving/running, so the engine never depends on its CWD."""
        self.files = [abspath_for(f, base_dir) if f else f for f in self.files]
        sections = [self.global_params, self.track_all] + list(self.tracks.values())
        for sec in sections:
            for key in _PATH_KEYS:
                if sec.get(key):
                    sec[key] = abspath_for(sec[key], base_dir)

    # ------------------------------------------------------------- writing
    def to_conf_text(self):
        lines = ["# Generated by RectChr GUI"]

        lines.append("")
        lines.append("SetParaFor=global")
        for i, f in enumerate(self.files):
            if f:
                lines.append("File%d=%s" % (i + 1, f))
        gparams = dict(self.global_params)
        if (self.tracks and self.track_num_explicit
                and "track_num" not in gparams):
            gparams["track_num"] = str(max(self.tracks))
        for k in sorted(gparams):
            if re.match(r"^File\d+$", k) or k == "FileX":
                continue                         # FileN lines come from self.files
            lines.append("%s=%s" % (k, quote_value(gparams[k], k)))

        if self.track_all:
            lines.append("")
            lines.append("SetParaFor=trackALL")
            for k in sorted(self.track_all):
                lines.append("%s=%s" % (k, quote_value(self.track_all[k], k)))

        for idx in sorted(self.tracks):
            tp = self.tracks[idx]
            lines.append("")
            lines.append("SetParaFor=track%d" % idx)
            for k in sorted(tp):
                lines.append("%s=%s" % (k, quote_value(tp[k], k)))

        lines.append("")
        return "\n".join(lines)

    def save(self, path):
        Path(path).write_text(self.to_conf_text(), encoding="utf-8")

    # ------------------------------------------------------------- reading
    @staticmethod
    def _engine_split(line):
        """Replicate the engine's comment/quote handling for one line."""
        line = line.strip().strip("\r")
        if not line or line.startswith("#"):
            return None
        line = line.replace('"#', "\x00")
        line = line.split("#")[0].split("##")[0]
        line = line.replace("\x00", '"#').replace('"', "").strip()
        m = _ENGINE_LINE.match(line)
        if not m:
            return None
        return m.group(1), m.group(2).strip()

    def load(self, path):
        self.files, self.global_params, self.track_all, self.tracks = [""], {}, {}, {}
        # relative data paths in a conf file are relative to the conf itself
        conf_dir = Path(path).resolve().parent
        section = "global"
        for raw in Path(path).read_text(encoding="utf-8", errors="replace").splitlines():
            kv = self._engine_split(raw)
            if kv is None:
                continue
            key, value = kv
            if key == "SetParaFor":
                name = value.replace("Level", "").replace("Track", "").replace("track", "")
                if name == "global":
                    section = "global"
                elif name == "ALL":
                    section = "ALL"
                elif name.isdigit():
                    section = int(name)
                continue
            if re.match(r"^File(\d+)$", key):
                idx = int(key[4:]) - 1
                while len(self.files) <= idx:
                    self.files.append("")
                self.files[idx] = abspath_for(value, conf_dir)
                continue
            key = Schema.resolve_alias(key)
            if key == "plot_type":
                value = Schema.resolve_plot_type(value)
            if key in _PATH_KEYS:
                value = abspath_for(value, conf_dir)
            if section == "global":
                self.global_params[key] = value
            elif section == "ALL":
                self.track_all[key] = value
            elif isinstance(section, int):
                self.tracks.setdefault(section, {})[key] = value
        # a conf that pinned track_num keeps controlling it; one that did not
        # stays implicit so the engine's own default is preserved on save
        self.track_num_explicit = "track_num" in self.global_params
        self.sync_track_num()
        return self
